AllCops:
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'spec/**/*'
    - 'test/**/*'

Metrics/MethodLength:
  Max: 25
Metrics/AbcSize:
  Max: 30
Metrics/CyclomaticComplexity:
  Max: 12
Metrics/PerceivedComplexity:
  Max: 12
Metrics/ClassLength:
  Max: 500
Metrics/BlockLength:
  Max: 30

Layout/LineLength:
  Max: 140
