# frozen_string_literal: true

require 'open3'
require 'fileutils'

module Mme
  # Handles Nmap scanning and importing
  class Scanner
    NMAP_DEFAULT_OPTS = '-sV -sC -T4 -Pn --open'
    NMAP_OUTPUT_FORMAT = '-oX'

    def initialize(framework, console_output = nil)
      @framework = framework
      @console_output = console_output
    end

    # Run an Nmap scan against an array of target IPs and import results
    def nmap_scan(targets, nmap_opts = nil, profile = :normal)
      unless nmap_available?
        log_error('Nmap is not installed or not in PATH')
        return []
      end

      unless @framework.db.active
        log_error('Database is not connected. Run db_connect first.')
        return []
      end

      if targets.empty?
        log_warning('No targets provided to Nmap scan.')
        return []
      end

      # Create temp file for Nmap XML output
      timestamp = Time.now.strftime('%Y%m%d_%H%M%S')
      output_dir = File.join(mme_data_dir, 'scans')
      FileUtils.mkdir_p(output_dir)
      output_file = File.join(output_dir, "nmap_#{timestamp}.xml")

      # Create input list file for Nmap
      input_list_file = File.join(output_dir, "nmap_targets_#{timestamp}.txt")
      File.write(input_list_file, targets.join("\n"))

      # Validate target input to prevent basic command injection (defense in depth)
      # Since we are using an input file (-iL), the injection risk on the command line is mitigated,
      # but we still want to ensure the IPs themselves are clean.
      invalid_targets = targets.reject { |t| t.match?(%r{^[a-zA-Z0-9.\-_/,:]+$}) }
      if invalid_targets.any?
        log_error("Invalid characters in target list. First offending target: #{invalid_targets.first}")
        return []
      end

      # Build Nmap command options
      opts = nmap_opts || NMAP_DEFAULT_OPTS
      if profile == :stealth
        opts = opts.gsub('-T4', '-T2')
        opts += ' --max-rate 50' unless opts.include?('--max-rate')
      end

      nmap_args = opts.split + [NMAP_OUTPUT_FORMAT, output_file, '-iL', input_list_file]

      log_status("Starting Nmap scan: nmap #{nmap_args.join(' ')}")
      log_status("Scanning #{targets.size} targets from Phase 0.")

      # Execute Nmap using array form to avoid shell interpolation
      begin
        # SECURITY: Array-form exec prevents shell interpolation/injection.
        output, status = Open3.capture2e('nmap', *nmap_args)
        unless status.success?
          log_error("Nmap scan failed: #{output}")
          return []
        end
        log_good("Nmap scan completed. Output: #{output_file}")
      rescue Errno::ENOENT
        log_error('Nmap executable not found. Please install Nmap.')
        return []
      rescue StandardError => e
        log_error("Nmap scan error: #{e.message}")
        return []
      ensure
        File.delete(input_list_file) if File.exist?(input_list_file)
      end

      # Import results
      import_file(output_file, targets)
    end

    # Import a scan results file (Nmap XML, Nessus, etc.)
    def import_file(path, targets = nil)
      unless File.exist?(path)
        log_error("File not found: #{path}")
        return []
      end

      unless @framework.db.active
        log_error('Database is not connected. Run db_connect first.')
        return []
      end

      log_status("Importing scan results: #{path}")

      begin
        # SECURITY: framework.db.import_file delegates to Msf::DBManager::Import
        # which uses its own hardened XML/JSON parsers. The file path is either
        # generated by us (nmap_scan) or provided by the operator via mme_import.
        # No user-controlled data reaches a shell here.
        @framework.db.import_file(filename: path)
        log_good("Successfully imported: #{path}")
      rescue StandardError => e
        log_error("Import failed: #{e.message}")
        return []
      end

      discover_services(targets)
    end

    # Query MSF database for open services in the current workspace
    def discover_services(targets = nil)
      unless @framework.db.active
        log_error('Database is not connected')
        return []
      end

      services = []
      workspace = @framework.db.workspace

      # If targets is an array (from Phase 0), we can join them for RangeWalker
      target_list = Array(targets)

      range_walker = nil
      if target_list.any?
        begin
          range_walker = ::Rex::Socket::RangeWalker.new(target_list.join(' '))
        rescue StandardError => e
          log_warning("Could not parse target range for filtering: #{e.message}")
        end
      end

      @framework.db.services(workspace: workspace).each do |svc|
        next unless svc.state == 'open'

        # Filter by targets if provided
        if range_walker && !range_walker.include?(svc.host.address)
          next
        end

        entry = ServiceEntry.new(
          host: svc.host.address,
          port: svc.port,
          proto: svc.proto,
          name: svc.name || '',
          info: svc.info || '',
          status: :pending
        )
        services << entry
      end

      log_good("Discovered #{services.size} open services across #{services.map(&:host).uniq.size} hosts")
      services
    end

    private

    def nmap_available?
      system('nmap --version > /dev/null 2>&1') || system('nmap --version > NUL 2>&1')
    rescue StandardError
      false
    end

    def mme_data_dir
      dir = File.join(Dir.home, '.msf4', 'mme')
      FileUtils.mkdir_p(dir)
      dir
    end

    def log_status(msg)
      @console_output ? @console_output.print_status(msg) : $stdout.puts("[*] #{msg}")
    end

    def log_good(msg)
      @console_output ? @console_output.print_good(msg) : $stdout.puts("[+] #{msg}")
    end

    def log_error(msg)
      @console_output ? @console_output.print_error(msg) : warn("[-] #{msg}")
    end
  end
end
